"no existe la clase '%s'", "no-existe-la-clase"
"'%s' no es una clase", "no-es-una-clase"
"no existe un método constructor", "no-existe-un-metodo-constructor"
"con 1 parámetro", "con-1-parametro"
"con %d parámetros", "con-parametros"
"sin parámetros", "sin-parametros"
"el constructor", "el-constructor"
"la función '%s'", "la-funcion"
"requiere 1 argumento", "requiere-1-argumento"
"requiere %d argumentos", "requiere-argumentos"
"no tiene argumentos", "no-tiene-argumentos"
"se ha intentado retornar sin estar dentro de función o método", "se-ha-intentado-retornar-sin-estar-dentro-de-funcion-o-metodo"
"operador izquierdo inválido", "operador-izquierdo-invalido"
"acceso no permitido", "acceso-no-permitido"
"índice no válido", "indice-no-valido"
"operador izquierdo no es un tipo válido", "operador-izquierdo-no-es-un-tipo-valido"
"no encontrado", "no-encontrado"
"'%s' no es un método válido", "no-es-un-metodo-valido"
"acceso no permitido", "acceso-no-permitido"
"'%s' no se ha encontrado", "no-se-ha-encontrado"
"función no encontrada", "funcion-no-encontrada"
"función no encontrada", "funcion-no-encontrada"
"el operador izquierdo de asignación es inválido", "el-operador-izquierdo-de-asignacion-es-invalido"
"tipo incorrecto", "tipo-incorrecto"
"tipo incorrecto", "tipo-incorrecto"
"símbolo no encontrado", "simbolo-no-encontrado"
"operador izquierdo no es válido", "operador-izquierdo-no-es-valido"
"tipos incompatibles", "tipos-incompatibles"
"no existe este método", "no-existe-este-metodo"
"el valor no es iterable", "el-valor-no-es-iterable"
"debe especificar un argumento", "debe-especificar-un-argumento"
"tipo incorrecto", "tipo-incorrecto"
"debe especificar dos argumentos", "debe-especificar-dos-argumentos"
"tipo incorrecto", "tipo-incorrecto"
"debe especificar dos argumentos", "debe-especificar-dos-argumentos"
"tipo incorrecto", "tipo-incorrecto"
"tipo incorrecto", "tipo-incorrecto"
"no se pudo convertir", "no-se-pudo-convertir"
"debe especificar al menos dos argumentos", "debe-especificar-al-menos-dos-argumentos"
"tipo incorrecto", "tipo-incorrecto"
"tipo incorrecto", "tipo-incorrecto"
"tipo incorrecto", "tipo-incorrecto"
"debe especificar un argumento", "debe-especificar-un-argumento"
"tipo incorrecto", "tipo-incorrecto"
"debe especificar al menos un argumento", "debe-especificar-al-menos-un-argumento"
"tipo incorrecto", "tipo-incorrecto"
"debe especificar un argumento", "debe-especificar-un-argumento"
"tipo incorrecto", "tipo-incorrecto"
"debe especificar un argumento", "debe-especificar-un-argumento"
"tipo incorrecto", "tipo-incorrecto"
"acceso no permitido", "acceso-no-permitido"
"acceso no permitido", "acceso-no-permitido"
"referencia fuera de clase", "referencia-fuera-de-clase"
"referencia fuera de clase", "referencia-fuera-de-clase"
"referencia fuera de clase", "referencia-fuera-de-clase"
"no existe clase padre de esta clase", "no-existe-clase-padre-de-esta-clase"
"tipo o formato incorrecto", "tipo-o-formato-incorrecto"
"la clave no puede ser nula", "la-clave-no-puede-ser-nula"
"tipo incorrecto", "tipo-incorrecto"
"símbolo no encontrado", "simbolo-no-encontrado"
"operador izquierdo de '%s' es inválido", "operador-izquierdo-de-es-invalido"
"acceso no permitido", "acceso-no-permitido"
"el símbolo '%s' ya fue definido", "el-simbolo-ya-fue-definido"
"el símbolo '%s' ya fue definido", "el-simbolo-ya-fue-definido"
"no existe la clase '%s'", "no-existe-la-clase"
"'%s' no es una clase", "no-es-una-clase"
"la clase padre no tiene ningún constructor", "la-clase-padre-no-tiene-ningun-constructor"
"con 1 argumentos", "con-1-argumentos"
"con %d argumentos", "con-argumentos"
"sin argumentos", "sin-argumentos"
"debe llamar al método constructor de la clase padre", "debe-llamar-al-metodo-constructor-de-la-clase-padre"
"se requiere un constructor para inicializar los atributos", "se-requiere-un-constructor-para-inicializar-los-atributos"