INSERT INTO textos (texto, slug, created_at, updated_at, created_by_id, updated_by_id, locale) VALUES
('no existe la clase \'%s\'', 'no-existe-la-clase', NOW(), NOW(), 1, 1, 'es'),
('\'%s\' no es una clase', 'no-es-una-clase', NOW(), NOW(), 1, 1, 'es'),
('no existe un método constructor', 'no-existe-un-metodo-constructor', NOW(), NOW(), 1, 1, 'es'),
('con un argumento', 'con-un-argumento', NOW(), NOW(), 1, 1, 'es'),
('con %d argumentos', 'con-argumentos', NOW(), NOW(), 1, 1, 'es'),
('sin argumentos', 'sin-argumentos', NOW(), NOW(), 1, 1, 'es'),
('el constructor', 'el-constructor', NOW(), NOW(), 1, 1, 'es'),
('la función \'%s\'', 'la-funcion', NOW(), NOW(), 1, 1, 'es'),
('requiere un argumento', 'requiere-un-argumento', NOW(), NOW(), 1, 1, 'es'),
('requiere %d argumentos', 'requiere-argumentos', NOW(), NOW(), 1, 1, 'es'),
('no tiene argumentos', 'no-tiene-argumentos', NOW(), NOW(), 1, 1, 'es'),
('se ha intentado retornar sin estar dentro de función o método', 'se-ha-intentado-retornar-sin-estar-dentro-de-funcion-o-metodo', NOW(), NOW(), 1, 1, 'es'),
('operador izquierdo inválido', 'operador-izquierdo-invalido', NOW(), NOW(), 1, 1, 'es'),
('acceso no permitido', 'acceso-no-permitido', NOW(), NOW(), 1, 1, 'es'),
('índice no válido', 'indice-no-valido', NOW(), NOW(), 1, 1, 'es'),
('operador izquierdo no es un tipo válido', 'operador-izquierdo-no-es-un-tipo-valido', NOW(), NOW(), 1, 1, 'es'),
('no encontrado', 'no-encontrado', NOW(), NOW(), 1, 1, 'es'),
('\'%s\' no es un método válido', 'no-es-un-metodo-valido', NOW(), NOW(), 1, 1, 'es'),
('\'%s\' no se ha encontrado', 'no-se-ha-encontrado', NOW(), NOW(), 1, 1, 'es'),
('función no encontrada', 'funcion-no-encontrada', NOW(), NOW(), 1, 1, 'es'),
('el operador izquierdo de asignación es inválido', 'el-operador-izquierdo-de-asignacion-es-invalido', NOW(), NOW(), 1, 1, 'es'),
('tipo incorrecto', 'tipo-incorrecto', NOW(), NOW(), 1, 1, 'es'),
('símbolo no encontrado', 'simbolo-no-encontrado', NOW(), NOW(), 1, 1, 'es'),
('operador izquierdo no es válido', 'operador-izquierdo-no-es-valido', NOW(), NOW(), 1, 1, 'es'),
('tipos incompatibles', 'tipos-incompatibles', NOW(), NOW(), 1, 1, 'es'),
('no existe este método', 'no-existe-este-metodo', NOW(), NOW(), 1, 1, 'es'),
('el valor no es iterable', 'el-valor-no-es-iterable', NOW(), NOW(), 1, 1, 'es'),
('debe especificar un argumento', 'debe-especificar-un-argumento', NOW(), NOW(), 1, 1, 'es'),
('debe especificar dos argumentos', 'debe-especificar-dos-argumentos', NOW(), NOW(), 1, 1, 'es'),
('no se pudo convertir', 'no-se-pudo-convertir', NOW(), NOW(), 1, 1, 'es'),
('debe especificar al menos dos argumentos', 'debe-especificar-al-menos-dos-argumentos', NOW(), NOW(), 1, 1, 'es'),
('debe especificar al menos un argumento', 'debe-especificar-al-menos-un-argumento', NOW(), NOW(), 1, 1, 'es'),
('referencia fuera de clase', 'referencia-fuera-de-clase', NOW(), NOW(), 1, 1, 'es'),
('no existe clase padre de esta clase', 'no-existe-clase-padre-de-esta-clase', NOW(), NOW(), 1, 1, 'es'),
('tipo o formato incorrecto', 'tipo-o-formato-incorrecto', NOW(), NOW(), 1, 1, 'es'),
('la clave no puede ser nula', 'la-clave-no-puede-ser-nula', NOW(), NOW(), 1, 1, 'es'),
('operador izquierdo de \'%s\' es inválido', 'operador-izquierdo-de-es-invalido', NOW(), NOW(), 1, 1, 'es'),
('el símbolo \'%s\' ya fue definido', 'el-simbolo-ya-fue-definido', NOW(), NOW(), 1, 1, 'es'),
('la clase padre no tiene ningún constructor', 'la-clase-padre-no-tiene-ningun-constructor', NOW(), NOW(), 1, 1, 'es'),
('debe llamar al método constructor de la clase padre', 'debe-llamar-al-metodo-constructor-de-la-clase-padre', NOW(), NOW(), 1, 1, 'es'),
('se requiere un constructor para inicializar los atributos', 'se-requiere-un-constructor-para-inicializar-los-atributos', NOW(), NOW(), 1, 1, 'es')